- hosts: all
  become: true

  tasks:
    - ansible.builtin.include_role:
        name: zfs
        tasks_from: dataset-check-exists.yml

    - ansible.builtin.include_role:
        name: libvirt
        tasks_from: vm-check-exists.yml

    - ansible.builtin.include_role:
        name: libvirt
        tasks_from: vm-confirm-info.yml

    - ansible.builtin.include_role:
        name: zfs
        tasks_from: dataset-confirm-info.yml

    - ansible.builtin.include_role:
        name: libvirt
        tasks_from: vm-undefine.yml

    - ansible.builtin.include_role:
        name: zfs
        tasks_from: dataset-destroy.yml
