- name: RedHat block
  when: ansible_os_family == "RedHat"
  block:
    - name: Install dnf-automatic (RedHat)
      ansible.builtin.package:
        name: dnf-automatic
        state: present

    - name: Enable dnf-automatic systemd service (RedHat)
      ansible.builtin.service:
        name: dnf-automatic-install.timer
        enabled: true
        state: started
