- name: Install prerequisite packages (if defined)
  ansible.builtin.package:
    name: "{{ guest_configure_packages_preq }}"
    state: present
  when: guest_configure_packages_preq | length > 0

- name: Install packages (if defined)
  ansible.builtin.package:
    name: "{{ guest_configure_packages }}"
    state: present
  when: guest_configure_packages | length > 0
