- name: Unregister guest with Red Hat Subscription Manager
  community.general.redhat_subscription:
    state: absent
  ignore_errors: true
  when:
    - (guest_configure_rhsm_username | length > 0) or (guest_configure_rhsm_org_id | length > 0) or (guest_configure_rhsm_satellite | length > 0)
