- name: Enable and start services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ guest_configure_services if guest_configure_services is iterable and guest_configure_services is not string else [] }}"
