- name: Import Red Hat Subscription Manager unregister task
  ansible.builtin.import_tasks: rhsm-unregister.yml
  when: (guest_configure_rhsm_username | length > 0) or (guest_configure_rhsm_org_id | length > 0)
