libvirt_vm_name: "{{ vm_name }}"
libvirt_vm_memory: "{{ memory_mb }}"
libvirt_vm_vcpus: "{{ cpus }}"
libvirt_vm_disk_size: "{{ disk_gb }}"
libvirt_vm_disk_format: "{{ disk_format }}"
libvirt_vm_os: "{{ os }}"
libvirt_vm_kickstart_file: "{{ kickstart }}"
libvirt_vm_iso_path: "{{ iso_path }}"
libvirt_vm_destination: "{{ parent_dataset }}/{{ vm_name }}"
libvirt_vm_network: "{{ network }}"
libvirt_kickstart_hostname: "{{ vm_name }}"
libvirt_kickstart_timezone: "{{ timezone }}"
libvirt_kickstart_root_ssh_key: "{{ root_ssh_key }}"
libvirt_kickstart_root_password: "{{ root_password }}"

