libvirt_vm_name: "{{ inventory_hostname }}"
libvirt_vm_memory: "{{ memory_mb if memory_mb is defined else '1024' }}"
libvirt_vm_vcpus: "{{ cpus if cpus is defined else '1' }}"
libvirt_vm_disk_size: "{{ disk_gb if disk_gb is defined else '20' }}"
libvirt_vm_disk_format: "{{ disk_format if disk_format is defined else 'qcow2' }}"
libvirt_vm_os: "{{ os if os is defined else 'rhel8-unknown' }}"
libvirt_vm_kickstart_file: "{{ kickstart if kickstart is defined }}"
libvirt_vm_location_path: "{{ iso_path }}"
libvirt_vm_destination: "{{ parent_dataset }}/{{ inventory_hostname }}"
libvirt_vm_network: "{{ network if network is defined else 'default' }}"
libvirt_kickstart_hostname: "{{ inventory_hostname }}"
libvirt_kickstart_timezone: "{{ timezone if timezone is defined else 'Etc/GMT' }}"
libvirt_kickstart_root_ssh_key: "{{ ssh_key if ssh_key is defined }}"
libvirt_kickstart_root_password: "{{ root_password if root_password is defined else lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
