ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
ansible_user: root
ansible_ssh_password: "{{ root_password if root_password is defined }}"

guest_configure_user: "{{ user if user is defined }}"
guest_configure_user_shell: "{{ shell if shell is defined }}"
guest_configure_ssh_keys: "{{ ssh_keys if ssh_keys is defined }}"
guest_configure_packages_preq: "{{ pre_packages if pre_packages is defined }}"
guest_configure_packages: "{{ packages if packages is defined }}"
guest_configure_services: "{{ services if services is defined }}"
guest_configure_rhsm_username: "{{ redhat_user if redhat_user is defined }}"
guest_configure_rhsm_password: "{{ redhat_password if redhat_password is defined }}"
guest_configure_rhsm_activation_key: "{{ redhat_activation_key if redhat_activation_key is defined }}"
guest_configure_rhsm_org_id: "{{ redhat_org_id if redhat_org_id is defined }}"
