# Vars can be set per-host, or globally under the vars: section
all:
  hosts:
    test-stream8:
      os: "rhel8-unknown" #A full list of OSes can be found with this #virt-install --osinfo list
      kickstart: "el8.ks"
      iso_path: "/path/to/ios/CentOS-Stream-8-20230612.0-x86_64-dvd1.iso"
      pre_packages: #Install these packages before regular ones
        - epel-release
      packages:
        - qemu-guest-agent
        - fish
      shell: "/usr/bin/fish" #Set shell for user
    test-rhel9:
      os: "rhel9-unknown"
      kickstart: "el9.ks"
      iso_path: "/path/to/isos/rhel-9.2-x86_64-dvd.iso"
      redhat_user: "rhsm_username" #Used for registering to Red Hat and un-registering when deleting VM
      redhat_password: "rhsm_password"
    test-f38:
      os: "fedora-unknown"
      kickstart: "f38.ks"
      iso_path: "/path/to/isos/Fedora-Server-dvd-x86_64-38-1.6.iso"
      libvirt_vm_location_arguments: ",kernel=images/pxeboot/vmlinuz,initrd=images/pxeboot/initrd.img" #https://bugzilla.redhat.com/show_bug.cgi?id=2144105
      packages:
        - qemu-guest-agent
        - fish
      shell: "/usr/bin/fish"
  vars:
    memory_mb: 1024
    cpus: 1
    disk_gb: 20
    disk_format: "raw"
    timezone: "America/New_York"
    hypervisor_host: "hypervisor.fqdn"
    parent_dataset: "zfs-parent-dataset/zfs-child-dataset"
    network: "bridge:vm-bridge"
#   root_password: "" #Not defining this will cause a random root password to be generated
    user: "admin" #Regular user with sudo rights
    # SSH key for root and regular user
    ssh_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFyY+3A07lMnHkyQ6bMez/BEi9j2vh4sotxQdqEMlCS+EJCta8G/CCj54kBvFKrrkiPMs0Jj1Od02ZjWZqGf+W/stZ+KLh97M0EM/69zbRbQJZ7xuCQKng7U87bbopbXcx9Mu9DUCC1pjNJ5Bb7nG6z51hk7mh3mF8QGHJ6qp03FrK+Eiud/2d9Zbn4lNH/E5W7iZ3J7zZHU16nLQH1Tsbx2LFUDkVhz/A4/7sqRmWT/mpwSCVgxN9cFgs1KMHsqb4Z1XXtbb//SWj+bmPvcfbfDUkTnb8Z+KTOd1OViKjDH1owgymxZtDML5S7OOZ2AX0/c5JaDplLRhji7gpVTRLZJE5XHvfVqwJCkxVrxoc4sbcZb9I/G+clJ3CBzSMZXh7p85J4OLVP5GmfOh0o93pakWVsTZBrPgO3EjhOyj0pGay3qUHiQfPqIlU+q92Mku5iijsbFDv28HdUlz5e69igg7E8Hr2/SruZuDijxOqkkHkmW0pnM8kXQpvU5dvW0U= pubkey@box
    packages: # Packages to install on guest
      - qemu-guest-agent
    services: # Services to enable on guest
      - qemu-guest-agent

