# Vars can be set per-host, or globally under the vars: section
all:
  hosts:
    test-stream8:
      os: "rhel8-unknown" #A full list of OSes can be found with this #virt-install --osinfo list
      kickstart: "el8.ks"
      iso_path: "/path/to/ios/CentOS-Stream-8-20230612.0-x86_64-dvd1.iso"
      pre_packages: #Install these packages before regular ones
        - epel-release
      packages:
        - qemu-guest-agent
        - fish
      shell: "/usr/bin/fish" #Set shell for user
    test-rhel9:
      os: "rhel9-unknown"
      kickstart: "el9.ks"
      iso_path: "/path/to/isos/rhel-9.2-x86_64-dvd.iso"
      redhat_user: "rhsm_username" #Used for registering to Red Hat and un-registering when deleting VM
      redhat_password: "rhsm_password"
    test-f38:
      os: "fedora-unknown"
      kickstart: "f38.ks"
      iso_path: "/path/to/isos/Fedora-Server-dvd-x86_64-38-1.6.iso"
      libvirt_vm_location_arguments: ",kernel=images/pxeboot/vmlinuz,initrd=images/pxeboot/initrd.img" #https://bugzilla.redhat.com/show_bug.cgi?id=2144105
      packages:
        - qemu-guest-agent
        - fish
      shell: "/usr/bin/fish"
  vars:
    memory_mb: 1024
    cpus: 1
#   cpu_type: "" This defaults to 'host-passthrough', however for Windows it can be defined as 'host' otherwise it will not install
    disk_gb: 20
    disk_format: "raw"
    timezone: "America/New_York"
    hypervisor_host: "hypervisor.fqdn"
    parent_dataset: "zfs-parent-dataset/zfs-child-dataset"
    network: "bridge:vm-bridge"
#   root_password: "" #Not defining this will cause a random root password to be generated for kickstart purposes
    user: "admin" #Regular user with sudo rights
    # SSH key for root and regular user - if no key or root password are defined, guest configuration will not run 
    ssh_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPqatKwhiSSePeDXU2VuoKzugIKWobA8U7QxsOxhQHJH"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP4AUk20x8I3Yxy8lDDCJNtGLdPl2yhHGJAluJ1hALtw"
    packages: # Packages to install on guest
      - qemu-guest-agent
    services: # Services to enable on guest
      - qemu-guest-agent

